# Apply common configuration to all hosts
- hosts: all
  roles:
  - common
  - tmpreaper
  - timezone

# - hosts: users
#   roles:

- hosts: gimnazjum
  roles:
  - network
  - dhcpd
  - auth
  - samba
  - auth

