# Apply common configuration to all hosts
- hosts: all
  roles:
  - tmpreaper
  - timezone
  - common
# - hosts: users
#   roles:

- hosts: gimnazjum
  roles:
          # - network
  - dhcpd
          #- auth
  - samba
    #- auth

