---

- name: samba is installed
  apt:  pkg=samba state=installed
  tags: samba

- name: fileserver prace
  file: path=/home/prace state=directory mode=0755 owner=root group=root
  tags: samba

# - name: samba share groups
#   group: name={{ item.group }} state=present
#   with_items: samba.shares
#   tags: samba
#
- name: ensure smbpassword is set
  raw:  (echo {{ item.smbpassword }}; echo {{ item.smbpassword }}) | smbpasswd -s -a {{ item.name }}
  with_items: users_to_add
  tags: samba
- name: samba share folders
  file: path="{{ item.path }}" state=directory mode=2770 owner={{ item.owner | default('nobody') }} group={{ item.group | default('nogroup')}}
  with_items: samba.shares
  tags: samba

- name: samba netlogon folder
  file: path=/var/lib/samba/netlogon state=directory mode=0755 owner=nobody group=nogroup

- name: samba netlogon file
  copy: src=netlogon/logon.cmd dest=/var/lib/samba/netlogon/logon.cmd owner=nobody group=nogroup mode=766

- name: samba config
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart samba
  tags: samba


- sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

