# file: roles/auth/tasks/users.yml

- name: Auth | Make sure the users are present
  user: name={{ item.name }}  password={{ item.password }} home={{item.home}} move_home={{item.move_home| default('no')}} shell={{item.shell| default('/bin/sh')}} groups={{ ",".join(item.groups) }} update_password=on_create
  with_items: "{{ users_to_add }}"
  when: users_to_add is defined
  ignore_errors: yes

- name: Create home folders
  file: path="{{ item.home | default("/home/{{ item.name }}" ) }}" state=directory mode=2750 owner={{ item.name | default('nobody') }} group={{ item.name | default('nogroup')}}
  with_items: "{{ users_to_add }}"
  when: users_to_add is defined

- name: set acls for nauczyciele home user rwx default
  acl: name={{ item.home | default("/home/{{ item.name}}") }} entity=nauczyciele etype=group permissions=rwx state=present default=yes
  with_items: "{{ users_to_add }}"
  when: users_to_add is defined
  ignore_errors: yes

- name: set acls for nauczyciele home user rwx not default
  acl: name={{item.home | default("/home/{{ item.name}}")}} entity=nauczyciele etype=group permissions=rwx state=present
  with_items: "{{ users_to_add }}"
  when: users_to_add is defined
  ignore_errors: yes


- name: set acls for nauczyciele prace
  acl: name=/home/prace entity=nauczyciele etype=group permissions=rwx state=present default=yes
  ignore_errors: yes
- name: set acls for nauczyciele prace
  acl: name=/home/prace entity=nauczyciele etype=group permissions=rwx state=present
  ignore_errors: yes

- name: set acls for nauczyciele informatyka
  acl: name=/home/informatyka entity=nauczyciele etype=group permissions=rwx state=present default=yes
  ignore_errors: yes
- name: set acls for nauczyciele informatyka
  acl: name=/home/informatyka entity=nauczyciele etype=group permissions=rwx state=present
  ignore_errors: yes

